export interface PersonParserResult {
  title: string;
  description: string;
  status: boolean;
  fields: any[];
}

const countries = [
  { name: 'Brasileira', id: '1' },
  { name: 'Outras', id: '99' },
  // { name: "Alemanha", id: "1" },
  // { name: "Argélia", id: "2" },
  // { name: "Argentina", id: "3" },
  // { name: "Armênia", id: "4" },
  // { name: "Austrália", id: "5" },
  // { name: "Áustria", id: "6" },
  // { name: "Bolívia", id: "7" },
  // { name: "Brasil", id: "8" },
  // { name: "Bulgária", id: "9" },
  // { name: "Chile", id: "10" },
  // { name: "China", id: "11" },
  // { name: "Colômbia", id: "12" },
  // { name: "Costa Rica", id: "13" },
  // { name: "Cuba", id: "14" },
  // { name: "Dinamarca", id: "15" },
  // { name: "Equador", id: "16" },
  // { name: "Espanha", id: "17" },
  // { name: "Estados Unidos", id: "18" },
  // { name: "França", id: "19" },
  // { name: "Irlanda", id: "20" },
  // { name: "Itália", id: "21" },
  // { name: "Japão", id: "22" },
  // { name: "México", id: "23" },
  // { name: "Nigéria", id: "24" },
  // { name: "Noruega", id: "25" },
  // { name: "Panamá", id: "26" },
  // { name: "Peru", id: "27" },
  // { name: "República Dominicana", id: "28" },
  // { name: "Suíça", id: "29" },
  // { name: "Venezuela", id: "30" },
];

const civilStatusList = [
  { id: 'married', name: 'Casado' },
  { id: 'single', name: 'Solteiro' },
  { id: 'divorced', name: 'Divorciado' },
  { id: 'widower', name: 'Viúvo' },
];

const genderList = [
  { id: 'male', name: 'Masculino' },
  { id: 'female', name: 'Feminino' },
  { id: 'other', name: 'Outro' },
];

const homeTypeList = [
  { id: 'own', name: 'Própria' },
  { id: 'rent', name: 'Alugada' },
  // { id: "other", name: "Outro" },
];

const bankAccountTypeList = [
  { id: 'current_account', name: 'Conta corrente' },
  { id: 'savings_account', name: 'Conta de poupança' },
  // { id: "overdrafts", name: "Check especial" },
  { id: 'other', name: 'Outro' },
];

const educationLevelList = [
  { id: 'primary', name: 'Ensino Fundamental' },
  { id: 'secondary', name: 'AlugadaEnsino Médio' },
  { id: 'tertiary', name: 'Bacharelado, Licenciado' },
];

/* const feeConceptList = [
  { id: "tac", name: "Tarifa de Cadastro" },
  { id: "ted_fee", name: "TED" },
  { id: "warranty_analysis", name: " Warranty Analysis" },
  { id: "rebate_over_trade_value", name: "Rebate over trade value" },
  { id: "registry_fee", name: "Registro de Contrato" },
]; */

//TODO: retrieve from DB
const stateGravamenList = [
  { stateCode: 'SP', stateName: 'São Paulo' },
  { stateCode: 'RJ', stateName: 'Rio de Janeiro' },
  { stateCode: 'PN', stateName: 'Paraná' },
  { stateCode: 'GO', stateName: 'Goiás' },
  { stateCode: 'MG', stateName: 'Minas Gerais' },
];

const dataTypeParser = (person: string) =>
  [
    {
      title: 'Dados Pessoais',
      description: '',
      status: true,
      fields: [
        {
          label: 'Nome Completo',
          type: 'text',
          mandatory: true,
          qiTechMandatory: true,
          max: 100,
          placeholder: '',
          name: `person.${person}.firstName`,
        },
        {
          label: 'Data de nascimento',
          type: 'date',
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.birthDate`,
        },
        {
          label: 'Local de Nascimento',
          type: 'text',
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.birthPlace`,
        },
        {
          label: 'Nacionalidade',
          type: 'option',
          mandatory: true,
          iTechMandatory: true,
          placeholder: '',
          options: countries.map(({ id, name }) => ({
            label: name,
            value: id,
          })),
          name: `person.${person}.birthCountry`,
        },
        {
          label: 'RG',
          type: 'text',
          max: 16,
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.rg`,
        },
        {
          label: 'Emissor',
          type: 'text',
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.emitter`,
        },
        {
          label: 'Data emissão',
          type: 'date',
          mandatory: false,
          qiTechMandatory: false, // Changed to false for testing
          placeholder: '', // TODO format
          name: `person.${person}.emitionDate`,
        },
        {
          label: 'Nome do Pai',
          type: 'text',
          max: 100,
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.fathersName`,
        },
        {
          label: 'Nome da Mãe',
          type: 'text',
          max: 100,
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.mothersName`,
        },
        {
          label: 'CPF',
          type: 'cpf',
          min: 11,
          max: 11,
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '878.938.938-89', // TODO format
          name: `person.${person}.citizenNumber`,
        },
        {
          label: 'CNH',
          type: 'text',
          min: 11,
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.cnh`,
        },
        {
          label: 'Sexo',
          type: 'option',
          options: genderList.map(({ id, name }) => ({
            label: name,
            value: id,
          })),
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.gender`,
        },
        {
          label: 'Estado Civil',
          type: 'option',
          mandatory: true,
          qiTechMandatory: true,
          options: civilStatusList.map(({ id, name }) => ({
            label: name,
            value: id,
          })),
          name: `person.${person}.civilStatus`,
        },
        {
          label: 'Nr. de Dependentes',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.dependents`,
        },
        {
          label: 'Escolaridade',
          type: 'option',
          mandatory: false,
          qiTechMandatory: false,
          options: educationLevelList.map(({ id, name }) => ({
            label: name,
            value: id,
          })),
          name: `person.${person}.studies`,
        },
      ],
    },
    {
      title: 'Endereço Residencial',
      description: '',
      status: false,
      fields: [
        {
          label: 'Tipo de Residência',
          type: 'option',
          options: homeTypeList.map(({ id, name }) => ({
            label: name,
            value: id,
          })),
          mandatory: true,
          qiTechMandatory: true,
          placeholder: 'Tipo de Residência',
          name: `person.${person}.homeType`,
        },
        {
          label: 'Valor mensal',
          type: 'text',
          mandatory: true,
          qiTechMandatory: true,
          placeholder: 'Valor mensal',
          name: `person.${person}.homeRent`,
        },
        {
          label: 'Tempo de residência',
          type: 'text',
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.homeAge`,
        },
        {
          label: 'Rua',
          type: 'text',
          mandatory: true,
          qiTechMandatory: true,
          max: 100,
          placeholder: '',
          name: `person.${person}.homeAddress`,
        },
        {
          label: 'Número',
          type: 'text',
          max: 10,
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '123',
          name: `person.${person}.homeAddressNumber`,
        },
        {
          label: 'Cometario',
          type: 'text',
          max: 100,
          mandatory: false,
          qiTechMandatory: false,
          placeholder: 'Piso, departamento, bloque, etc.',
          name: `person.${person}.homeComments`,
        },
        {
          label: 'Bairro',
          type: 'text',
          max: 100,
          mandatory: true,
          qiTechMandatory: true,
          placeholder: 'Bairro',
          name: `person.${person}.homeNeighbour`,
        },
        {
          label: 'CEP',
          type: 'text',
          max: 8,
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.homeCep`,
        },
        {
          label: 'Cidade',
          type: 'text',
          max: 100,
          mandatory: true,
          qiTechMandatory: true,
          placeholder: 'Cidade',
          name: `person.${person}.homeCity`,
        },
        {
          label: 'Estado',
          type: 'option',
          options: stateGravamenList.map(({ stateCode, stateName }) => ({
            label: stateName,
            value: stateCode,
          })),
          name: `person.${person}.homeState`,
        },
        {
          label: 'Tel. Number',
          type: 'phone',
          max: 15,
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.homePhone`,
        },
        {
          label: 'Cel. Number',
          type: 'phone',
          mandatory: true,
          max: 15,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.cellPhone`,
        },
        {
          label: 'E-mail pessoal',
          type: 'email',
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.personalEmail`,
        },
        {
          label: 'E-mail profissional',
          type: 'email',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.professionalEmail`,
        },
      ],
    },
    {
      title: 'Dados de Trabalho',
      description: '',
      status: false,
      fields: [
        {
          label: 'Profissão',
          type: 'text',
          max: 64,
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.profession`,
        },
        {
          label: 'PeP',
          type: 'checkbox',
          mandatory: true,
          qiTechMandatory: true,
          name: `person.${person}.isPep`,
        },
        {
          label: 'Empresa',
          type: 'text',
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.companyName`,
        },
        {
          label: 'CNPJ',
          type: 'text',
          max: 14,
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.companyCnpj`,
        },
        {
          label: 'Telefone da empresa',
          type: 'phone',
          max: 15,
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.companyPhone`,
        },
        {
          label: 'Bairro',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.companyNeighbour`,
        },
        {
          label: 'CEP',
          type: 'text',
          max: 8,
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.companyCep`,
        },

        {
          label: 'Cidade',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          max: 100,
          placeholder: '',
          name: `person.${person}.companyCity`,
        },
        {
          label: 'Estado',
          type: 'option',
          options: stateGravamenList.map(({ stateCode, stateName }) => ({
            label: stateName,
            value: stateCode,
          })),
          name: `person.${person}.companyState`,
        },
        {
          label: 'Cargo',
          type: 'text',
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.companyJobPossition`,
        },
        {
          label: 'Vínculo',
          type: 'text',
          mandatory: true,
          qiTechMandatory: true,
          placeholder: '',
          name: `person.${person}.companyRelation`,
        },
        {
          label: 'Data de admissão',
          type: 'date',
          mandatory: true,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.companyStartDate`,
        },
        {
          label: 'Renda principal',
          type: 'text',
          mandatory: true,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.companyMainSalaryAmount`,
        },
        // {
        //   label: "Comprovação",
        //   type: "text",
        //   mandatory: true,
        //qiTechMandatory: true,
        //   placeholder: "",
        //   name: `person.${person}.companyMainSalaryCheck`,
        // },
        {
          label: 'Renda adicional',
          type: 'text',
          mandatory: true,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.companySecondaryAmount`,
        },
        // {
        //   label: "Comprovação",
        //   type: "text",
        //   mandatory: true,
        //qiTechMandatory: true,
        //   placeholder: "",
        //   name: `person.${person}.companySecondaryCheck`,
        // },
      ],
    },
    {
      title: 'Referências Bancárias',
      description: '',
      status: true,
      fields: [
        {
          label: 'Banco',
          type: 'text',
          mandatory: true,
          qiTechMandatory: true,
          max: 50,
          placeholder: '',
          name: `person.${person}.bankName`,
        },
        {
          label: 'Cliente desde',
          type: 'date',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.bankFromDate`,
        },
        {
          label: 'Exp. Crédito',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.bankCredit`,
        },
        {
          label: 'Tipo de conta',
          type: 'option',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          options: bankAccountTypeList.map(({ id, name }) => ({
            label: name,
            value: id,
          })),
          name: `person.${person}.bankAccountType`,
        },
        {
          label: 'Agência',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.bankAgency`,
        },
        {
          label: 'Número da conta',
          type: 'text',
          max: 10,
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.bankAccountNumber`,
        },
        {
          label: 'Limite Cheque Especial',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.bankCheckLimit`,
        },
        {
          label: 'Contato',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.bankContactName`,
        },
        {
          label: 'Telefone',
          type: 'phone',
          max: 15,
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.bankContactPhone`,
        },
      ],
    },
    {
      title: 'Bens',
      description: '',
      status: false,
      fields: [
        {
          label: 'Descrição',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.goodsDescription`,
        },
        {
          label: 'Tipo',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.goodsType`,
        },
        {
          label: 'Valor',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.goodsValue`,
        },
        {
          label: 'Endereço',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.goodsAddress`,
        },
        {
          label: 'Possui ônus?',
          type: 'checkbox',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.hadGravamen`,
        },
        {
          label: 'Valor do ônus e valor da parcela:',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.gravamenValue`,
        },
        {
          label: 'Se veículo',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.car`,
        },
        {
          label: 'Marca',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.carBrand`,
        },
        {
          label: 'Modelo',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.carModel`,
        },
        {
          label: 'Cor',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.carColor`,
        },
        {
          label: 'Ano/Modelo',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.carYear`,
        },
        {
          label: 'Placa',
          type: 'text',
          mandatory: false,
          qiTechMandatory: false,
          placeholder: '',
          name: `person.${person}.carPlate`,
        },
      ],
    },
  ] as PersonParserResult[];

export { dataTypeParser };
