import { Inventory } from '../models/Inventory';
import { Lead } from '../models/Lead';
import { LoanApplicationRevision } from '../models/LoanApplicationRevision';
import { Offer } from '../models/Offer';
import { Person } from '../models/Person';
import { Quote } from '../models/Quote';
import { Profile } from '../models/Profile';

export interface LoanApplicationDTO {
  id?: number;
  userId?: number;
  offerId?: number;
  consumerLoanRequestId?: number;
  inventoryId?: number;
  leadId?: number;
  status?: string;
  cnpj?: string;
  company?: string;
  createdAt?: Date;
  updatedAt?: Date;
  expiresAt?: Date;
  vehicleType?: string;
  vehicleBrand?: string;
  vehicleModel?: string;
  vehicleModelYear?: string;
  vehicleColor?: string;
  vehiclePlate?: string;
  vehicleYear?: string;
  vehicleChasis?: string;
  vehicleValue?: string;
  vehicleDoors?: string;
  vehicleRenavam?: string;
  addressVoucher?: any;
  rentVoucher?: any;
  rg?: any;
  cosignerAddressVoucher?: any;
  cosignerRentVoucher?: any;
  cosignerRg?: any;
  auxiliarDocument1?: any;
  auxiliarDocument2?: any;
  auxiliarDocument3?: any;
  vehicleRegistryCertificate?: any;
  vehicleDealersInvoice?: any;
  user?: Profile;
  lead?: Lead;
  offer?: Offer;
  quote?: Quote;
  inventory?: Inventory;
  revisions?: LoanApplicationRevision[];
  person?: { buyer?: Person; garant?: Person; couple?: Person };
}
